version: "2"
services:
    ssl_proxy:
        image: cbachich/docker-ssl-proxy
        ports:
        - "443:443"
        links:
        - web:proxyapp
        environment:
            PORT: 443
            TARGET_PORT: 80
    web:
        build: .
        ports:
        - "80:80"
        volumes: 
        - .:/var/www
        environment:
            DEBUG: 1